menu:
    Blog: /
    Archive: archives/
    Feed: atom.xml

favicon: favicon.png
logo: favicon.png

# Comment
# e.g disqus: claymcleod 
disqus:

# Analytics
ga: UA-212844417-1

# Copyright Infomation
startyear: 2019

# Image Credits
enable_image_credit: true 
